### ISSUE TITLE
ADIOS install error in LINUX

### ISSUE THREAD

**Issue by sumnepa** [ornladios/ADIOS#157]
Hello,
I am trying to install ADIOS in LINUX and it does not build. It gives me following error:

> libtool  --tag=CC   --mode=link gcc  -g -O2 -L/home/user1/gts-install//lib    -pthread -o bpls bpls-bpls.o ../../src/libadiosread_nompi.a -levpath  -libverbs   -lm 
libtool: link: gcc -g -O2 -pthread -o bpls bpls-bpls.o  -L/home/user1/gts-install//lib ../../src/libadiosread_nompi.a /home/user1/gts-install/lib/libevpath.so -libverbs -lm -pthread -Wl,-rpath -Wl,/home/user1/gts-install/lib -Wl,-rpath -Wl,/home/user1/gts-install/lib
/usr/bin/ld: ../../src/libadiosread_nompi.a(libadiosread_nompi_a-read_flexpath.o): undefined reference to symbol 'FMfree_struct_list'
/home/user1/gts-install/lib/libffs.so.1: error adding symbols: DSO missing from command line

My configuration is as follows:

> ./configure --prefix=/home/usr1/gts-install/adios-install  --with-mxml=path-to-mxml --with-hdf5=path-to-hdf5 --with-netcdf=path-to-netcdf --with-flexpath=path-to-flexpath --with-zlib=path-to-zlib --with-szip=path-to-szip --with-mpi=path-to-mpi

What could be done to get by this error. I have used the source files from git repository and also used adios-1.12.0.
Thank you.

**Comment by eisenhauer** [comment]
We haven't seen this problem in general on Linux platforms, so we might have to ask some questions to sort out what is going on.  The libffs.so.1 library that is "missing", is part of the dependency set of libevpath.so.  Normally, we'd expect the linker to pull in those dependencies based upon info in the .so file.  However, it's safer to list them all obviously.  I *suspect* that this problem has something to do with the interactions between libtool (used to build ADIOS) and a dummy libtool library that is installed with EVPath (dummy because EVPath isn't built with libtool).  However, I think the first step is to sort out how you are building the EVPath library set.  Particularly, if you are building EVPath with the version tagged "adios-1.12" that might not work at all with the github copy of ADIOS.  So maybe the first step would be to fetch a newer version of EVPath.  Can you try building EVPath with the "stable" tag rather than the "adios-1.12" tag?  That brings in all-but-bleeding-edge EVPath.  Let me know if you need instructions on how to do this..

greg

**Comment by sumnepa** [comment]
Hello,
I installed EVPath and ffs using the source files from following location:

> svn co http://svn.research.cc.gatech.edu/kaos/ffs/trunk ffs 
svn co http://svn.research.cc.gatech.edu/kaos/evpath/trunk evpath 

So, I haven't mentioned any stable tag and I don't see any such tag while installing them.
Can you please tell me where to mention the tag?

**Comment by sumnepa** [comment]
Oh!, nevermind I figured that out and it installs perfectly after the stable installation of EVPath. Thank you.
