### ISSUE TITLE
Using multiple groups in a single .bp file.

### ISSUE THREAD

**Issue by Jorispilot** [ornladios/ADIOS#66]
Is it possible to use multiple groups in a single .bp file, each group containing different variables, mesh, etc. from each other?
If so, how should I proceed? I did not see any example in the repository.

**Comment by pnorbert** [comment]
Yes, it is possible with some limitations:
- cannot have the same variable (path) in both groups because the reading API presents all variables in one list
- you must write the two groups separately in an adios_open...adios_write...adios_close cycle. Which means you don't gain performance over writing them to two separate files.
- it also means that you cannot use staging methods meaningfully, only file based reading. So no in-situ viz.
- there was a bug since 1.8.0 which caused segfault if you had more than one meshes in the file. This was just fixed in 988671bb578e1ecb98, so it will be working in the next release again (you see, not many people are using this feature).

To do this, just have two groups defined as usual, and use the same output file name when you write each group.
