### ISSUE TITLE
Python: Is File Open?

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#73]
@yyalli currently it is not possible to query if a `f=adios.File` object is still open (e.g., after a call to `.close()`).

One way would be to implement a cast of `adios.File` to `bool` (as `h5py` does it) which leads `True` if the internal `f.fp` is `!= NULL` and `False` otherwise.

Alternatively, an `f.is_open()` call could be implemented with the same behaviour.

This is necessary to finish our HDFCompass pull request (https://github.com/HDFGroup/hdf-compass/issues/155).

**Comment by yyalli** [comment]
Just implemented is_open() as well as boolean cast functions (__nonzero__ and __bool__) for adios file.

--
Jong Youl Choi
Scientific Data Group
Computer Science and Math Division
Oak Ridge National Laboratory
Homepage: http://www.ornl.gov/~jyc/

On Jul 6, 2016, at 10:05 AM, Axel Huebl <notifications@github.com<mailto:notifications@github.com>> wrote:


@yyalli<https://github.com/yyalli> currently it is not possible to query if a adios.File object is still open.

One way would be to implement a cast of adios.File to bool (as h5py does it) which leads True if the internal fp is != NULL and False otherwise.

Alternatively, an f.is<http://f.is>_open() call could be implemented with the same behaviour.

This is necessary to finish our HDFCompass pull request (HDFGroup/hdf-compass#155<https://github.com/HDFGroup/hdf-compass/issues/155>).

**Comment by ax3l** [comment]
Hi Jong, that's awesome and quick! We will try it tomorrow, thank you so much.

**Comment by ax3l** [comment]
wonderful, I tested it and it works!
b1038dea0145e46474b610163a184c000c371566

**Comment by ax3l** [comment]
ccing @michaelsippel
